
kind: pipeline
name: first

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - pip install flask pytest
  - pytest
  when:
    changeset:
      includes: [ test* ]
---

kind: pipeline
name: second

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - echo -n ciaooooo_
  - echo come va?
  when:
    changeset:
      includes: [ test* ]
