

kind: pipeline
name: second

steps:
- name: test_b_1
  image: python:3.7-alpine
  commands:
  - echo -n ciaooooo_
  - echo come va?
  when:
    changeset:
      includes: [ test* ]
- name: test_b_2
  image: python:3.7-alpine
  commands:
  - echo -n ciaooooo_
  - echo come stai?
  when:
    changeset:
      includes: [ test* ]
