

kind: pipeline
name: first

steps:
- name: test_a_1
  image: python:3.7-alpine
  commands:
  - echo $DRONE_REMOTE_URL
  - echo $DRONE_GIT_HTTP_URL
  - echo $DRONE_GIT_SSH_URL
  - echo come va?
  when:
    changeset:
      includes:
        - "test*"
        - "*.yml"

---

kind: pipeline
name: second

steps:
- name: test_b_1
  image: python:3.7-alpine
  commands:
  - echo -n ciaooooo_
  - echo come va?
  when:
    changeset:
      includes: [ test* ]
- name: test_b_2
  image: python:3.7-alpine
  commands:
  - echo -n ciaooooo_
  - echo come stai?
  when:
    changeset:
      includes: [ test* ]
